// This model is for Ander code challenge
const mongoose = require("mongoose");

// Create a schema - how a post should look like (a description)
// id will be auto generated by MongoDB when pushing to DB
const UserSchema = mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  score: {
    type: Number,
    required: true
  }
});

module.exports = mongoose.model("asdasdasd", UserSchema);
